<?php
/**
 * DoctrineResourceListenerInterface.php
 * Generated by PhpStorm - 07/2016
 * Project APIFirstBundle
 * @author Beno!t POLASZEK
 **/

namespace BenTools\ApiFirstBundle\Model;

interface DoctrineResourceListenerInterface {

}