<?php
/**
 * DoctrineResourceListenerInterface.php
 * Generated by PhpStorm - 07/2016
 * Project APIFirstBundle
 * @author Beno!t POLASZEK
 **/

namespace BenTools\ApiFirstBundle\Model;

/**
 * Interface DoctrineResourceListenerInterface
 * @link http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/events.html#entity-listeners-class
 */
interface DoctrineResourceListenerInterface {

}